name: Daily Scheduled Job

on:
  schedule:
    - cron: '1,* * * * *'  # Every day at 9 AM UTC
  workflow_dispatch:     # Allows manual triggering (optional)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run echo script
      run: echo "Hello! This is your daily scheduled GitHub Action job."

